_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: e6dfb109-d1c1-4b89-a9ea-69f0994f3041
name: Drupal
mail: arijit.acharya@innoraft.com
slogan: ''
page:
  403: /node/3
  404: /node/2
  front: /node/168
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
